### ISSUE TITLE
Node v10+ causes Error: Cannot find module 'bindings'

### ISSUE THREAD

**Issue by ambiguities** [wadey/node-microtime#59]
Steps to reproduce:

https://npm.runkit.com/microtime

Set to node v10
```
var microtime = require("microtime")
microtime.now()
```
Causes:
```
Error: Cannot find module 'bindings'
at Module._resolveFilename in core internal/modules/cjs/loader.js — line 571
at Module._load in core internal/modules/cjs/loader.js — line 497
at Module.require in core internal/modules/cjs/loader.js — line 626
at require in core internal/modules/cjs/helpers.js — line 20
in microtime/index.js — line 1
at Module._compile in core internal/modules/cjs/loader.js — line 678
at Module._extensions..js in core internal/modules/cjs/loader.js — line 689
at Module.load in core internal/modules/cjs/loader.js — line 589
at tryModuleLoad in core internal/modules/cjs/loader.js — line 528
at Module._load in core internal/modules/cjs/loader.js — line 520
at Module.require in core internal/modules/cjs/loader.js — line 626
at Object.require in core internal/modules/cjs/helpers.js — line 20
in this notebook — line 1
at Generator.next in core — line 0
at Generator.next in core — line 0
```

**Comment by wadey** [comment]
Thanks for the report, I'm preparing a build for Node 10 now.

**Comment by wadey** [comment]
Microtime 2.1.8 published with support for Node 10. Please try updating and let me know.

**Comment by wadey** [comment]
Closing because I have not heard back, but version 2.1.8 should fix this issue.

**Comment by mawrkus** [comment]
Unfortunately I think it's not fixed :(

**Steps to reproduce:**

Go to https://npm.runkit.com/microtime

**Set to node v10.14.1**

```javascript
var microtime = require("microtime")
microtime.now()
```

**Result**

```
Error: Could not locate the bindings file. Tried:
 → /app/available_modules/1545311051000/microtime/build/microtime.node
 → /app/available_modules/1545311051000/microtime/build/Debug/microtime.node
 → /app/available_modules/1545311051000/microtime/build/Release/microtime.node
 → /app/available_modules/1545311051000/microtime/out/Debug/microtime.node
 → /app/available_modules/1545311051000/microtime/Debug/microtime.node
 → /app/available_modules/1545311051000/microtime/out/Release/microtime.node
 → /app/available_modules/1545311051000/microtime/Release/microtime.node
 → /app/available_modules/1545311051000/microtime/build/default/microtime.node
 → /app/available_modules/1545311051000/microtime/compiled/10.14.1/linux/x64/microtime.node
```

I also noticed this error on a node:10.14.2-stretch-slim Docker image with Python installed:

```
Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
    at Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Object.nodeDevHook [as .node] (/usr/src/app/node_modules/node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (/usr/src/app/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/src/app/node_modules/microtime/index.js:1:34)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

Hope this helps.

**Comment by wadey** [comment]
@mawrkus I've released microtime 3.0.0 using N-API, so let me know if this is fixed with 3.0.0.
